name: CD

on:
  push:
    tags:
      - '*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Branch env
        run: |
          echo "SOURCE_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "SOURCE_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm/v6
          push: true
          tags: |
            yuuki0805/pyicloud:${{ env.SOURCE_TAG }}
            yuuki0805/pyicloud:latest
            yuuki0805/pyicloud:alpine
